// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAwAUUUlGy6uBPakLk5f-V0Rc7LzQkI2Gk",
      authDomain: "papabear-8b9f9.firebaseapp.com",
      projectId: "papabear-8b9f9",
      storageBucket: "papabear-8b9f9.firebasestorage.app",
      messagingSenderId: "442389815451",
      appId: "1:442389815451:web:a73b94a0e478f2d008263e",
      measurementId: "G-92YJ3NVYHK");

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwAUUUlGy6uBPakLk5f-V0Rc7LzQkI2Gk',
    appId: '1:442389815451:ios:0acee7711c0d203e08263e',
    messagingSenderId: '442389815451',
    projectId: 'papabear-8b9f9',
    storageBucket: 'papabear-8b9f9.firebasestorage.app',
    iosClientId:
        '1022022823127-sslblmdd2adkjrnuallnbfonpd087ina.apps.googleusercontent.com',
    iosBundleId: 'com.papabear.userapp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEg2nu09HpaaEjNqxsvwqCGZ2p47vYu4s',
    appId: '1:442389815451:android:942b8dfb7fd1a4ac08263e',
    messagingSenderId: '442389815451',
    projectId: 'papabear-8b9f9',
    storageBucket: 'papabear-8b9f9.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa5Nzkwem00XC1By9KPyzlrsQjeoAzz-g',
    appId: '1:1022022823127:ios:3168d26b57581ab6f3d492',
    messagingSenderId: '1022022823127',
    projectId: 'ultimate-salon-flutter',
    storageBucket: 'ultimate-salon-flutter.appspot.com',
    iosClientId:
        '1022022823127-oepg48gm1mb8nl3hclr2frtj4kt14lje.apps.googleusercontent.com',
    iosBundleId: 'com.example.salonUser.RunnerTests',
  );
}
